name: medbioinforub-ident-comparison
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - pip
  - setuptools
  - git
  # rust is needed as long as the ms2rescore.rs is not updated
  - rust=1.86.0
  - pip:
    - -r requirements.txt
